org: jsusvel
service: api-s3

provider:
  name: aws
  runtime: python3.12	
  # Default memory size for functions (default: 256MB)
  memorySize: 256
  timeout: 30
  iam:
    role: arn:aws:iam::692614634256:role/LabRole

functions:
  create_bucket:
    handler: create_bucket.create_bucket
    memorySize: 512
    events:
      - http:
          path: /s3/create-bucket
          method: post
          cors: true
          integration: lambda

  create_directory:
    handler: create_directory.create_directory
    memorySize: 512
    events:
      - http:
          path: /s3/create-directory
          method: post
          cors: true
          integration: lambda

  upload_file:
    handler: upload_file.upload_file
    memorySize: 512
    events:
      - http:
          path: /s3/upload
          method: post
          cors: true
          integration: lambda
